### ISSUE TITLE
Server doesn't install with npm

### ISSUE THREAD

**Issue by JCCChris** [wdmtech/feathers-vuex-todomvc#1]
says "npm ERR! 404 Not Found - GET https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz"

**Comment by wdmtech** [comment]
Thanks @JCCChris, will take a look - probably needs bringing up-to-date

**Comment by wdmtech** [comment]
Looks like it Feathers needs to be updated - PR welcomed if you can do it. If not I'll try to get around to it soon!

**Comment by JCCChris** [comment]
Thanks for the update!

**Comment by wdmtech** [comment]
No worries :-D
